### ISSUE TITLE
Prepare Chapter 4

### ISSUE THREAD

**Issue by phaazon** [phaazon/learn-luminance#16]
# Let’s prepare chapter 4!

The goal of this ticket is to track what we might want to teach people in chapter 4.

## List of topics people are interested in

- Geometry instancing.
- Texturing.
- Blending.

**Comment by ottworks** [comment]
* Use of multiple shaders and associated interface types
* Mixing 2d rendering and 3d rendering (for user interfaces)
* Text rendering with rusttype
* Deferred rendering
* Example systems to un-hardcode various aspects of the sample program

**Comment by phaazon** [comment]
Closing as I’m going to rewrite everything, but I will take all of that into account.
