### ISSUE TITLE
Stating CMake is a requirement to use Luminance

### ISSUE THREAD

**Issue by Perregrinne** [phaazon/learn-luminance#28]
It might be a good idea to state in the requirements table in chapter 1.1. Getting Started that CMake is required, or when compiling, one may get a `panic` asking, "is `cmake` not installed?" as I did. I have not tested this on platforms other than Windows 10 (there's a chance that Linux or MacOS systems may ship with CMake, so not everyone may get this when going through the tutorial).

**Comment by phaazon** [comment]
I’m closing as I’m going to rewrite everything after the new luminance design lands.
