### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by adri326** [phaazon/learn-luminance#32]
First of all, thank you for this tutorial, my mind was melting with all of the documentation that I had to sift through until I stumbled onto your tutorial.

Unfortunately, the link to a rendered version of this tutorial is currently broken (https://rust-tutorials.github.io/learn-luminance/).
I could read the tutorial off the github page, the only real downside there was the increased number of tabs that I had to open as a result.

**Comment by phaazon** [comment]
Closing as I’m going to rewrite everything.
